name: Deploy Docs

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write 

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # if your docs needs submodules, uncomment the following line
          # submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Deploy Docs
        uses: intergiro/vuepress-deploy@fix_git_repo  # Update back to jenkey2011/vuepress-deploy@master once merged
        env:
          GITHUB_DEPLOY: true
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_REPO: em-c-rod/sw-doc-training
          TARGET_BRANCH: gh-pages
          BUILD_SCRIPT: npm ci && npm run docs:build
          BUILD_DIR: .vuepress/dist/
